/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./index.html", "./src/**/*.{js,jsx,ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#4edea3",
        "on-tertiary-fixed": "#002113",
        "primary-fixed-dim": "#ffb3b1",
        "on-secondary": "#ffffff",
        "inverse-primary": "#ffb3b1",
        "inverse-surface": "#213145",
        "on-secondary-container": "#5c647a",
        "error-container": "#ffdad6",
        background: "#f8f9ff",
        "secondary-fixed-dim": "#bec6e0",
        "surface-container-low": "#eff4ff",
        "surface-tint": "#bf002a",
        "on-surface": "#0b1c30",
        surface: "#f8f9ff",
        "on-primary-container": "#ffedec",
        "on-surface-variant": "#5d3f3e",
        "outline-variant": "#e7bcbb",
        "on-tertiary-container": "#bdffdb",
        "secondary-container": "#dae2fd",
        "on-primary-fixed": "#410008",
        "surface-variant": "#d3e4fe",
        "secondary-fixed": "#dae2fd",
        "on-secondary-fixed": "#131b2e",
        "on-error-container": "#93000a",
        "surface-bright": "#f8f9ff",
        secondary: "#565e74",
        "on-primary": "#ffffff",
        "on-secondary-fixed-variant": "#3f465c",
        "surface-container-high": "#dce9ff",
        "tertiary-container": "#007d55",
        "primary-fixed": "#ffdad8",
        outline: "#926e6d",
        "surface-dim": "#cbdbf5",
        tertiary: "#006242",
        "primary-container": "#dc0032",
        primary: "#ae0025",
        error: "#ba1a1a",
        "on-background": "#0b1c30",
        "on-tertiary": "#ffffff",
        "tertiary-fixed": "#6ffbbe",
        "inverse-on-surface": "#eaf1ff",
        "on-error": "#ffffff",
        "surface-container": "#e5eeff",
        "surface-container-highest": "#d3e4fe",
        "on-tertiary-fixed-variant": "#005236",
        "on-primary-fixed-variant": "#92001e",
        "surface-container-lowest": "#ffffff",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "space-3xl": "4rem",
        "gutter-desktop": "2rem",
        "container-max": "88rem",
        "space-xl": "2rem",
        "gutter-mobile": "1rem",
        "space-sm": "0.75rem",
        "space-3xs": "0.125rem",
        "space-2xs": "0.25rem",
        "space-2xl": "3rem",
        "gutter-tablet": "1.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xs": "0.5rem",
      },
      fontFamily: {
        "body-lg": ["Hanken Grotesk", "sans-serif"],
        "mono-data-cell": ["JetBrains Mono", "monospace"],
        "title-sm": ["Hanken Grotesk", "sans-serif"],
        "headline-md": ["Hanken Grotesk", "sans-serif"],
        "display-lg": ["Hanken Grotesk", "sans-serif"],
        "headline-xl": ["Hanken Grotesk", "sans-serif"],
        "body-md": ["Hanken Grotesk", "sans-serif"],
        "mono-currency": ["JetBrains Mono", "monospace"],
        "body-sm": ["Hanken Grotesk", "sans-serif"],
        "headline-xl-mobile": ["Hanken Grotesk", "sans-serif"],
        "display-lg-mobile": ["Hanken Grotesk", "sans-serif"],
        "label-caps": ["Hanken Grotesk", "sans-serif"],
      },
      fontSize: {
        "body-lg": ["1rem", { lineHeight: "1.5rem", letterSpacing: "0", fontWeight: "400" }],
        "mono-data-cell": ["0.8125rem", { lineHeight: "1.125rem", letterSpacing: "-0.01em", fontWeight: "500" }],
        "title-sm": ["1.125rem", { lineHeight: "1.5rem", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-md": ["1.5rem", { lineHeight: "2rem", letterSpacing: "-0.015em", fontWeight: "600" }],
        "display-lg": ["3rem", { lineHeight: "3.5rem", letterSpacing: "-0.025em", fontWeight: "700" }],
        "headline-xl": ["2rem", { lineHeight: "2.5rem", letterSpacing: "-0.02em", fontWeight: "600" }],
        "body-md": ["0.875rem", { lineHeight: "1.25rem", letterSpacing: "0", fontWeight: "400" }],
        "mono-currency": ["1.25rem", { lineHeight: "1.5rem", letterSpacing: "-0.02em", fontWeight: "600" }],
        "body-sm": ["0.75rem", { lineHeight: "1rem", letterSpacing: "0.01em", fontWeight: "400" }],
        "headline-xl-mobile": ["1.75rem", { lineHeight: "2.25rem", letterSpacing: "-0.015em", fontWeight: "600" }],
        "display-lg-mobile": ["2.25rem", { lineHeight: "2.75rem", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-caps": ["0.6875rem", { lineHeight: "0.875rem", letterSpacing: "0.08em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};
